// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/strat-solver/StratSolver.tsx": () => import("../components/mockups/strat-solver/StratSolver.tsx")
};
